version: "3.7"

services:
  database:
    image: postgres
    volumes:
      - ./private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - encurtador-de-links-network
networks:
  encurtador-de-links-network:
    driver: bridge
